language: node_js
node_js:
 - "node"

install:
 - git submodule init
 - git submodule update
 - npm install -g bower
 - npm install -g karma-cli
 - npm install
 - bower install
 - cd infrastructure/functions
 - npm install
 - cd -
 - npm run build
 - npm test